version: "3"
services:
    db:
        image: "postgres"
        environment:
            POSTGRES_USER: me
            POSTGRES_PASSWORD: password
            POSTGRES_DATABASE: api
        ports:
          - 5432:5432
        volumes:
          - db-data:/var/lib/postgres
    web:
        build: .
        environment:
            DB_NAME: api
            DB_PASSWORD: password
            DB_USER: me
            DB_HOST: db
            DB_PORT: 5432
        ports:
          - "3000:3000"
        depends_on:
          - db

volumes:
    db-data:
